import React from 'react';
import {useParams,Link} from 'react-router-dom';
import {features} from '@/data/features';
import Page,{Intro,TrialCTA} from '@/components/shared/Page';
import PageNotFound from '@/lib/PageNotFound';
export default function FeatureDetail(){
 const {slug}=useParams();const f=features.find(x=>x.slug===slug);if(!f)return <PageNotFound/>;
 const questions=[{question:`What can I do with ${f.name.toLowerCase()}?`,answer:f.overview},{question:`Which plans include ${f.name.toLowerCase()}?`,answer:f.plan},...(f.faq||[])];
 const schema=[{'@type':'BreadcrumbList',itemListElement:[['Home','/'],['Features','/features'],[f.name,'/features/'+slug]].map(([name,path],i)=>({'@type':'ListItem',position:i+1,name,item:'https://www.fuzedflow.com'+path}))},{'@type':'WebPage',name:f.name,description:f.overview,url:'https://www.fuzedflow.com/features/'+slug},{'@type':'FAQPage',mainEntity:questions.map(q=>({'@type':'Question',name:q.question,acceptedAnswer:{'@type':'Answer',text:q.answer}}))}];
 return <Page title={f.seoTitle||`${f.name} for contractors`} description={f.description||f.tagline+' '+f.overview.slice(0,95)} path={'/features/'+slug} schema={schema}><div className="ff-shell"><Intro eyebrow={f.group} title={f.headline||f.tagline} description={f.overview}/><div className="ff-plan-note"><strong>Plan availability:</strong> {f.plan} <Link to="/pricing">Compare plans →</Link></div><section className="ff-section"><h2>How {f.name.toLowerCase()} works</h2><ol className="ff-step-grid">{f.howItWorks.map((step,i)=><li key={step}><span>{String(i+1).padStart(2,'0')}</span><p>{step}</p></li>)}</ol></section><section className="ff-example"><p className="ff-eyebrow">Worked example</p><h2>What this looks like on a job</h2><p>{f.example}</p><p className="text-sm mt-4">Illustrative workflow. Prices and scope are examples, not customer results.</p></section><section className="ff-section"><h2>Questions about {f.name.toLowerCase()}</h2>{questions.map(q=><details className="ff-faq" key={q.question}><summary>{q.question}</summary><p>{q.answer}</p></details>)}</section><section className="ff-section"><h2>Connected workflows</h2><div className="ff-card-grid">{f.related.map(slug=>features.find(x=>x.slug===slug)).filter(Boolean).map(x=><Link className="ff-card" key={x.slug} to={'/features/'+x.slug}><h3>{x.name}</h3><p>{x.tagline}</p><span>Explore workflow →</span></Link>)}</div><p className="mt-5"><Link to="/integrations">See external integrations and CSV migration →</Link></p></section><div className="ff-cta-strip"><div><h2>See the workflow with your own job.</h2><p>Choose a plan or request a walkthrough with the Fuzed Flow team.</p></div><TrialCTA/></div></div></Page>;
}
