import React from 'react';
import {Link} from 'react-router-dom';
import Page,{TrialCTA} from '@/components/shared/Page';
import {PricingCards} from './Pricing';
import {features} from '@/data/features';
import DemoForm from '@/components/forms/DemoForm';
import ROICalculator from '@/components/home/ROICalculator';
const assets='https://ochqexofahdssmarnict.supabase.co/storage/v1/object/public/screenshots/';
export default function Home(){return <Page title="Contractor software from enquiry to invoice" description="Connect leads, phased quotes, project materials, crew records and invoices in Fuzed Flow. Plans from $29 USD/month with a 14-day trial." path="/" schema={[{'@type':'Organization',name:'Fuzed Flow',url:'https://www.fuzedflow.com',logo:'https://ochqexofahdssmarnict.supabase.co/storage/v1/object/public/logos/fuzed-flow-storefront-logo.svg',contactPoint:{'@type':'ContactPoint',contactType:'customer support',email:'support@fuzedflow.com'}},{'@type':'SoftwareApplication',name:'Fuzed Flow',applicationCategory:'BusinessApplication',operatingSystem:'Web browser',url:'https://www.fuzedflow.com',offers:{'@type':'Offer',price:'29',priceCurrency:'USD',url:'https://www.fuzedflow.com/pricing'}}]}>
 <section className="ff-hero"><div className="ff-shell"><div className="ff-hero-grid"><div><p className="ff-eyebrow">For contractors who run the job</p><h1>From the first enquiry to the final invoice.</h1><p className="ff-lead">Quote the scope. Plan the work. Keep the office and crew working from connected records in one contractor workspace.</p><div className="ff-hero-actions"><TrialCTA/><a className="ff-button ff-button-outline" href="/contact#demo" data-event="demo_cta">See your workflow in a demo</a></div><p className="ff-hero-note">Starter $29 · Professional $59 · Business $159 USD/month</p></div><figure className="ff-hero-image"><img src={assets+'contractor-estimating-software-quote-builder.webp'} alt="Fuzed Flow quote builder with phased contractor scope and line items" width="1440" height="900" fetchPriority="high"/><figcaption>Start with clear scope, costs and options.</figcaption></figure></div></div></section>
 <section id="how-it-works" className="ff-shell ff-section"><p className="ff-eyebrow">A connected job story</p><h2>Carry the right details into the next step.</h2><p className="ff-lead max-w-3xl">Every stage has a record: the enquiry, approved quote, project material list, site update and remaining invoice balance.</p><ol className="ff-step-grid">{[['Capture the enquiry','Keep the contact, site, photos and next follow-up together.','lead-management'],['Agree on the scope','Build phased quotes and let clients choose optional items.','estimating'],['Organize the job','Plan phases, import selected materials and assign tasks.','project-management'],['Record and invoice','Save site records, approve changes and review payments.','invoicing']].map(([title,detail,slug],i)=><li key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{detail}</p><Link to={'/features/'+slug}>See the workflow →</Link></li>)}</ol><Link className="ff-button ff-button-outline" to="/workflow-example">Follow a worked renovation example →</Link></section>
 <section className="ff-band"><div className="ff-shell ff-section"><p className="ff-eyebrow">Office, project manager, crew and client</p><h2>The right view for the next decision.</h2><div className="ff-card-grid">{[['Office','Follow enquiries, reuse quote scope, send documents and review invoice balances.','estimating'],['Project manager','See phase dates, tasks, material ordering, issues, plans and trade documents.','project-management'],['Crew','Open assigned work, clock hours and submit receipts or site notes in the web portal.','employee-portal'],['Client','Review quote options, approve scope and open invoice payment links.','client-portal']].map(([title,body,slug])=><Link className="ff-card" to={'/features/'+slug} key={title}><h3>{title}</h3><p>{body}</p><span>Explore the view →</span></Link>)}</div><p className="text-sm mt-6">Employee portal and HR: Professional and Business. Client access covers shared documents.</p></div></section>
 <section className="ff-shell ff-section"><div className="ff-screen-story"><figure><img loading="lazy" decoding="async" width="1440" height="900" src={assets+'construction-project-management-workspace.webp'} alt="Fuzed Flow project workspace with phase and site records"/><figcaption>Project records stay with the job.</figcaption></figure><div><p className="ff-eyebrow">Useful details, less searching</p><h2>Know what needs attention.</h2><p>A material can be Ordered while a phase is Blocked and a task is assigned to the crew. See those records in context, then decide the next action.</p><ul className="ff-check-list"><li>Selected quote items become project materials.</li><li>Drawing revisions and permit attachments stay with the project.</li><li>Current contractor links share selected scope and files.</li></ul><Link className="ff-button ff-button-outline" to="/features/project-materials">See the material workflow →</Link></div></div></section>
 <section id="features" className="ff-shell ff-section"><p className="ff-eyebrow">Explore the platform</p><h2>Start with the work you do every week.</h2><div className="ff-card-grid">{['estimating','smart-templates','pricebook','project-management','project-materials','contractor-portal','invoicing','time-tracking'].map(slug=>features.find(f=>f.slug===slug)).map(f=><Link className="ff-card" key={f.slug} to={'/features/'+f.slug}><h3>{f.name}</h3><p>{f.tagline}</p><span>View the steps →</span></Link>)}</div><Link className="inline-block mt-6 font-bold" to="/features">Explore all 21 workflows →</Link></section>
 <section className="ff-band"><div className="ff-shell ff-section"><p className="ff-eyebrow">Make a useful start</p><h2>Get help with the next step.</h2><div className="ff-card-grid"><div className="ff-card"><h3>Ask AI Help</h3><p>“How do I import materials from a quote?” Product help returns relevant written guides and app routes so you can follow the steps.</p><Link to="/faq#team-help">See what AI Help does →</Link></div><Link className="ff-card" to="/resources"><h3>Use a practical resource</h3><p>Start with an estimate checklist, change-order outline, daily-log example, timesheet CSV or margin calculation.</p><span>Get the resources →</span></Link><Link className="ff-card" to="/integrations"><h3>Bring supported records across</h3><p>Use CSV imports for leads, client contacts and inventory. Review the connection status before planning an accounting integration.</p><span>Check integrations →</span></Link></div></div></section>
 <section className="ff-shell ff-section"><ROICalculator/></section>
 <section id="pricing" className="ff-shell ff-section"><p className="ff-eyebrow">USD pricing · 14-day trial</p><h2>Choose the workspace for your crew.</h2><PricingCards/><Link className="inline-block font-bold" to="/pricing">Compare every plan feature →</Link></section>
 <section id="demo" className="ff-demo"><div className="ff-shell grid gap-12 py-16 lg:grid-cols-2"><div><p className="ff-eyebrow">Walk through your workflow</p><h2>Bring the questions from your next job.</h2><p className="ff-lead">Tell us your trade, crew size and the work you want to connect. We’ll use that context for your walkthrough.</p><div className="ff-topic-links">{[['Renovations','renovation-contractors'],['General contractors','general-contractors'],['Home builders','home-builders']].map(([name,slug])=><Link key={slug} to={'/industries/'+slug}>{name} →</Link>)}</div></div><DemoForm/></div></section>
 </Page>;}
