import React from 'react';
import {renderToString} from 'react-dom/server';
import {StaticRouter} from 'react-router-dom/server';
import {Routes,Route} from 'react-router-dom';
import {HelmetProvider} from 'react-helmet-async';
import Home from './pages/Home';
import Features from './pages/Features';
import FeatureDetail from './pages/FeatureDetail';
import Pricing from './pages/Pricing';
import Integrations from './pages/Integrations';
import Resources from './pages/Resources';
import Industry from './pages/Industry';
import WorkflowExample from './pages/WorkflowExample';
import FAQ from './pages/FAQ';
import Contact from './pages/Contact';
import Terms from './pages/Terms';
import Privacy from './pages/Privacy';
import PageNotFound from './lib/PageNotFound';
export function render(url){const context={};const html=renderToString(<HelmetProvider context={context}><StaticRouter location={url}><React.Suspense fallback={<div role="status" className="p-10">Loading Fuzed Flow…</div>}><Routes><Route path="/" element={<Home/>}/><Route path="/features" element={<Features/>}/><Route path="/features/:slug" element={<FeatureDetail/>}/><Route path="/pricing" element={<Pricing/>}/><Route path="/integrations" element={<Integrations/>}/><Route path="/resources" element={<Resources/>}/><Route path="/resources/:slug" element={<Resources/>}/><Route path="/industries/:slug" element={<Industry/>}/><Route path="/workflow-example" element={<WorkflowExample/>}/><Route path="/faq" element={<FAQ/>}/><Route path="/contact" element={<Contact/>}/><Route path="/terms" element={<Terms/>}/><Route path="/privacy" element={<Privacy/>}/><Route path="*" element={<PageNotFound/>}/></Routes></React.Suspense></StaticRouter></HelmetProvider>);const h=context.helmet;return {html,head:h.title.toString()+h.meta.toString()+h.link.toString()+h.script.toString()};}
