import React,{useState} from 'react';
import {trackEvent} from '@/lib/analytics';
export default function DemoForm({kind='demo'}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 async function submit(event){event.preventDefault();const form=event.currentTarget;const fields=Object.fromEntries(new FormData(form));setBusy(true);setError('');trackEvent('enquiry_submit',{kind});
  try{const response=await fetch('https://ochqexofahdssmarnict.supabase.co/functions/v1/storefront-enquiry',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`,apikey:import.meta.env.VITE_SUPABASE_ANON_KEY},body:JSON.stringify({...fields,kind})});const result=await response.json();if(!response.ok||result.error)throw new Error(result.error||'Request could not be saved.');setDone(true);form.reset();trackEvent('enquiry_success',{kind});}
  catch{setError('Your request could not be saved. Please try again or email support@fuzedflow.com.');trackEvent('enquiry_error',{kind});}finally{setBusy(false);}
 }
 if(done)return <div className="ff-form-success" role="status"><h3>Request received</h3><p>Thanks. The Fuzed Flow team will reply to the email address you provided.</p><button className="ff-button mt-5" onClick={()=>setDone(false)}>Send another request</button></div>;
 return <form className="ff-form" onSubmit={submit}><div className="grid gap-5 sm:grid-cols-2"><label>Full name *<input name="name" required maxLength={120} autoComplete="name"/></label><label>Email *<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>Company<input name="company" maxLength={150} autoComplete="organization"/></label><label>Phone <span className="font-normal">(optional)</span><input name="phone" type="tel" maxLength={40} autoComplete="tel"/></label></div><label className="ff-honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label>Your workflow / question<textarea name="message" maxLength={4000} rows={4} placeholder="Tell us about your trade, crew and the job workflow you want to see."/></label>{kind==='demo'&&<label>Preferred date <span className="font-normal">(optional)</span><input name="preferred_date" type="date"/></label>}<p className="text-sm">We use these details to reply to your request. <a href="/privacy">Privacy policy</a></p>{error&&<p className="ff-form-error" role="alert">{error}</p>}<button className="ff-button" disabled={busy} type="submit">{busy?'Sending…':kind==='demo'?'Request a demo':'Send message'}</button></form>;
}
